// Check tab: the validator and the solver (run after every save), and a screenshot of a room at a checkpoint.
import { heatFill } from '@engine/tools/puzzle';
import { profileText, type SolveProfile } from '@engine/tools/solve';
import {
  api,
  type CoverageData,
  type GameInfo,
  type GraphData,
  type LintData,
  type PlaytestsData,
  type PuzzleData,
  type ReportData,
  type SolveData,
  type ValidateResult,
} from './api';
import { append, h, select, toast } from './ui';

/** An SVG string as a node (the graph is generated by the engine, not by user input). */
function svgNode(svg: string): HTMLElement {
  const box = h('div', { class: 'svgbox' });
  box.innerHTML = svg;
  return box;
}

export class CheckTab {
  readonly el = h('section', { class: 'tab check' });
  private v: ValidateResult | null = null;
  private s: SolveData | null = null;
  private r: ReportData | null = null;
  private g: GraphData | null = null;
  private p: PuzzleData | null = null;
  private c: CoverageData | null = null;
  private l: LintData | null = null;
  private pt: PlaytestsData | null = null;
  /** Which heat the puzzle graph shows: none, the solver's runs, the players' sessions. */
  private heatSource: 'none' | 'solver' | 'playtests' = 'none';
  private card = h('pre', { class: 'md card' });
  /** Puzzle graph toggles: fade everything off the critical path; colour nodes by how often the solver went through them. */
  private focus = false;
  private heat = false;
  private err = '';
  private running = false;
  private from = '';
  private shotRoom: string;
  private shotCp = '';
  private timer: ReturnType<typeof setTimeout> | undefined;
  private out = h('div', { class: 'checkout' });
  private shot = h('div', { class: 'shot' });
  private runBtn = h('button', { class: 'primary', onclick: () => void this.run() }, 'Run again');
  private stamp = h('span', { class: 'muted small' });

  constructor(
    info: GameInfo,
    private badge: (state: 'ok' | 'warn' | 'error' | 'busy', text: string) => void,
    private open?: (room: string, path: string) => void,
  ) {
    this.shotRoom = info.rooms[0]?.id ?? '';
    const cps: [string, string][] = Object.entries(info.checkpoints).map(([k, c]) => [k, `${k} (${c.room})`]);
    const shotBtn = h('button', { onclick: () => void this.screenshot() }, 'Screenshot room at checkpoint');
    this.el.append(
      h(
        'div',
        { class: 'bar' },
        this.runBtn,
        h(
          'label',
          null,
          'Solve from ',
          select(
            [['', 'New game'], ...cps],
            this.from,
            (x) => {
              this.from = x;
              void this.run();
            },
            { 'aria-label': 'Solve from' },
          ),
        ),
        this.stamp,
      ),
      h(
        'div',
        { class: 'checkgrid' },
        this.out,
        // Screenshots render the room with Playwright on the dev server: not in the demo.
        api.mode === 'demo'
          ? null
          : h(
              'div',
              { class: 'panel' },
              h('h3', null, 'Screenshot'),
              h(
                'div',
                { class: 'bar' },
                select(
                  info.rooms.map((r) => [r.id, r.name]),
                  this.shotRoom,
                  (x) => {
                    this.shotRoom = x;
                  },
                  { 'aria-label': 'Room to screenshot' },
                ),
                select(
                  [['', 'auto state'], ...cps],
                  this.shotCp,
                  (x) => {
                    this.shotCp = x;
                  },
                  { 'aria-label': 'Checkpoint' },
                ),
                shotBtn,
              ),
              this.shot,
            ),
      ),
    );
    this.render();
  }

  /** Run soon (debounced): after every save. */
  schedule(ms = 700) {
    clearTimeout(this.timer);
    this.timer = setTimeout(() => void this.run(), ms);
  }

  async run() {
    if (this.running) {
      this.schedule(400);
      return;
    }
    this.running = true;
    this.runBtn.disabled = true;
    this.badge('busy', '…');
    try {
      this.err = '';
      this.v = await api.validate();
      this.s = await api.solve(this.from);
      this.g = await api.graph().catch(() => null);
      this.r = await api.report().catch(() => null);
      this.p = await api.puzzle().catch(() => null);
      this.c = await api.coverage().catch(() => null);
      this.l = await api.lint().catch(() => null);
      this.pt = api.playtests ? await api.playtests().catch(() => null) : null;
    } catch (e) {
      this.err = (e as Error).message;
    } finally {
      this.running = false;
      this.runBtn.disabled = false;
      this.stamp.textContent = `checked at ${new Date().toLocaleTimeString()}`;
      this.render();
    }
  }

  private render() {
    const { v, s } = this;
    if (this.err) this.badge('error', '!');
    else if (v && s) {
      const bad = v.errors.length + s.errors.length + (s.exit === 0 ? 0 : 1);
      this.badge(
        bad ? 'error' : v.warnings.length ? 'warn' : 'ok',
        bad ? String(bad) : v.warnings.length ? String(v.warnings.length) : '✔',
      );
    }
    if (!v && !s && !this.err) {
      this.out.replaceChildren(h('p', { class: 'muted' }, 'Not run yet.'));
      return;
    }
    this.out.replaceChildren();
    append(this.out, [
      this.err ? h('p', { class: 'error' }, this.err) : null,
      ...(v
        ? [
            h(
              'div',
              { class: 'panel' },
              h(
                'h3',
                null,
                'Validator ',
                h('span', { class: v.ok ? 'ok' : 'bad' }, v.ok ? '✔ no error' : `✖ ${v.errors.length} error(s)`),
                h('span', { class: 'muted small' }, ` ${v.warnings.length} warning(s) · ${v.ms} ms`),
              ),
              v.errors.length
                ? h(
                    'ul',
                    { class: 'msgs errors' },
                    v.errors.map((e) => h('li', null, e)),
                  )
                : null,
              v.warnings.length
                ? h(
                    'ul',
                    { class: 'msgs warnings' },
                    v.warnings.map((e) => h('li', null, e)),
                  )
                : null,
            ),
          ]
        : []),
      ...(s
        ? [
            h(
              'div',
              { class: 'panel' },
              h(
                'h3',
                null,
                'Solver ',
                h('span', { class: s.exit === 0 ? 'ok' : 'bad' }, `${s.exit === 0 ? '✔' : '✖'} ${s.headline}`),
                h('span', { class: 'muted small' }, ` ${s.mode} · from ${s.from ?? 'a new game'} · ${s.ms} ms`),
              ),
              s.errors.length
                ? h(
                    'ul',
                    { class: 'msgs errors' },
                    s.errors.map((e) => h('li', null, e)),
                  )
                : null,
              s.broken?.length
                ? h(
                    'ul',
                    { class: 'msgs errors' },
                    s.broken.map((b) =>
                      h(
                        'li',
                        null,
                        `invariant #${b.invariant} became true after: ${b.path.slice(-3).join(' › ') || 'the start'}`,
                      ),
                    ),
                  )
                : null,
              h(
                'ol',
                { class: 'path' },
                s.path.map((p) => h('li', null, p)),
              ),
              h(
                'dl',
                { class: 'facts' },
                h('dt', null, 'Rooms reached'),
                h('dd', null, s.roomsReached.join(', ') || '—'),
                h('dt', null, 'Unlocked'),
                h('dd', null, s.unlockedReached.join(', ') || '—'),
                s.itemsNeverUsed.length
                  ? [h('dt', null, 'Items never used'), h('dd', null, s.itemsNeverUsed.join(', '))]
                  : null,
                s.unusedItems.length
                  ? [h('dt', null, 'Items never obtained'), h('dd', null, s.unusedItems.join(', '))]
                  : null,
              ),
              s.deadEnds.length
                ? h(
                    'div',
                    null,
                    h('h4', null, `Dead ends (${s.deadEnds.length})`),
                    h(
                      'ul',
                      { class: 'msgs warnings' },
                      s.deadEnds
                        .slice(0, 8)
                        .map((d) =>
                          h(
                            'li',
                            null,
                            `${d.room}, [${d.inventory.join(', ')}] after ${d.path.slice(-3).join(' › ') || 'the start'}`,
                          ),
                        ),
                    ),
                  )
                : null,
              s.profile ? this.health(s.profile) : null,
            ),
          ]
        : []),
      ...(this.g
        ? [
            h(
              'div',
              { class: 'panel world' },
              h(
                'h3',
                null,
                'World ',
                h(
                  'span',
                  { class: 'muted small' },
                  `${this.g.graph.rooms.length} rooms · exits solid, gotos dashed, ◎ on the map`,
                ),
              ),
              this.g.graph.unreachable.length
                ? h('p', { class: 'error' }, `Unreachable: ${this.g.graph.unreachable.join(', ')}`)
                : null,
              this.g.graph.oneWay.length
                ? h(
                    'p',
                    { class: 'warnings' },
                    `No way back: ${this.g.graph.oneWay.map((e) => `${e.from} → ${e.to} (${e.via})`).join(', ')}`,
                  )
                : null,
              svgNode(this.g.svg),
            ),
          ]
        : []),
      ...(this.p
        ? [
            h(
              'div',
              { class: 'panel puzzles' },
              h(
                'h3',
                null,
                'Puzzles ',
                h(
                  'span',
                  { class: 'muted small' },
                  `${this.p.graph.nodes.length} nodes · tap an item, flag or prop for its card · green: produces, red: consumes, dotted: read inside`,
                ),
              ),
              h(
                'div',
                { class: 'bar' },
                h(
                  'label',
                  { title: 'Keep only what leads to the end, a goal or an invariant; the rest fades' },
                  h('input', {
                    type: 'checkbox',
                    checked: this.focus,
                    onchange: (ev: Event) => {
                      this.focus = (ev.target as HTMLInputElement).checked;
                      this.restyle();
                    },
                  }),
                  ' Critical path',
                ),
                h(
                  'label',
                  {
                    title:
                      'Colour each rule, topic, listener, script and room by how many times the solver, or the players, went through it',
                  },
                  ' Heat ',
                  h(
                    'select',
                    {
                      onchange: (ev: Event) => {
                        this.heatSource = (ev.target as HTMLSelectElement).value as CheckTab['heatSource'];
                        this.heat = this.heatSource !== 'none';
                        this.restyle();
                      },
                    },
                    h('option', { value: 'none', selected: this.heatSource === 'none' }, 'none'),
                    h(
                      'option',
                      { value: 'solver', selected: this.heatSource === 'solver', disabled: !s?.profile },
                      'solver',
                    ),
                    h(
                      'option',
                      { value: 'playtests', selected: this.heatSource === 'playtests', disabled: !this.pt?.files },
                      `playtests${this.pt?.files ? ` (${this.pt.files})` : ''}`,
                    ),
                  ),
                ),
                h(
                  'span',
                  { class: 'muted small' },
                  `${Object.values(this.p.classes).filter((c) => c === 'critical').length} critical · ${Object.values(this.p.classes).filter((c) => c === 'dead').length} out of the solver's state`,
                ),
              ),
              this.puzzleSvg(this.p.svg),
              this.card,
              h('details', null, h('summary', null, 'Overview'), h('pre', { class: 'md' }, this.p.markdown)),
            ),
          ]
        : []),
      ...(this.pt
        ? [
            h(
              'div',
              { class: 'panel playtests' },
              h(
                'h3',
                null,
                'Playtests ',
                h(
                  'span',
                  { class: 'muted small' },
                  `${this.pt.files} session(s) · ${this.pt.report.total.entries} inputs · ${this.pt.report.stalls.length} stall(s) · ${this.pt.report.divergences} outgrown · ${this.pt.ms} ms · the same text the playtests tool returns`,
                ),
              ),
              h('pre', { class: 'md' }, this.pt.markdown),
            ),
          ]
        : []),
      ...(this.l
        ? [
            h(
              'div',
              { class: 'panel lint' },
              h(
                'h3',
                null,
                'Content lint ',
                h(
                  'span',
                  {
                    class: `cov ${this.l.lint.counts.error ? 'missing' : this.l.lint.counts.warning ? 'partial' : 'ok'}`,
                  },
                  `${this.l.lint.counts.error} ✖ · ${this.l.lint.counts.warning} ⚠ · ${this.l.lint.counts.info} ℹ`,
                ),
                h(
                  'span',
                  { class: 'muted small' },
                  ` ${this.l.mode} solve · ${this.l.lint.ignored} ignored · ${this.l.ms} ms · the same text the lint tool returns · \`lint.ignore\` in game.ts silences a code`,
                ),
              ),
              this.l.lint.findings.length
                ? h(
                    'ul',
                    { class: 'msgs findings' },
                    this.l.lint.findings.map((f) =>
                      h(
                        'li',
                        { class: f.severity },
                        h('code', null, f.code),
                        ' ',
                        f.where.room
                          ? h(
                              'a',
                              {
                                href: `#rooms/${f.where.room}`,
                                title: 'Open in Rooms',
                                onclick: (ev: Event) => {
                                  ev.preventDefault();
                                  this.open?.(f.where.room!, f.where.path);
                                },
                              },
                              `${f.where.room}/${f.where.path}`,
                            )
                          : h('span', null, f.where.path),
                        f.where.id ? h('span', { class: 'muted small' }, ` ${f.where.id}`) : null,
                        h('div', null, f.message),
                        h('div', { class: 'muted small' }, `→ ${f.fix}`),
                      ),
                    ),
                  )
                : h('p', { class: 'muted small' }, 'Nothing to report.'),
            ),
          ]
        : []),
      ...(this.c
        ? [
            h(
              'div',
              { class: 'panel coverage' },
              h(
                'h3',
                null,
                'Storyboard coverage ',
                h(
                  'span',
                  {
                    class: `cov ${this.c.coverage.score >= 0.95 ? 'ok' : this.c.coverage.score >= 0.7 ? 'partial' : 'missing'}`,
                  },
                  `${Math.round(this.c.coverage.score * 100)}%`,
                ),
                h(
                  'span',
                  { class: 'muted small' },
                  ` ${this.c.coverage.totals.ok} implemented · ${this.c.coverage.totals.partial} partial · ${this.c.coverage.totals.missing} missing · ${this.c.coverage.totals.unknown} not checked · ${this.c.ms} ms · the same text the storyboard_coverage tool returns`,
                ),
              ),
              h('pre', { class: 'md' }, this.c.markdown),
            ),
          ]
        : []),
      ...(this.r
        ? [
            h(
              'div',
              { class: 'panel report' },
              h(
                'h3',
                null,
                'Content report ',
                h(
                  'span',
                  { class: 'muted small' },
                  `${this.r.report.totals.lines} lines · ${this.r.report.totals.words} words · ${this.r.ms} ms`,
                ),
              ),
              h('pre', { class: 'md' }, this.r.markdown),
            ),
          ]
        : []),
    ]);
  }

  private svgBox: HTMLElement | null = null;

  /** The puzzle SVG, with a card for the tapped node (its `data-node` id). */
  private puzzleSvg(svg: string): HTMLElement {
    const box = svgNode(svg);
    box.addEventListener('click', (ev) => {
      const g = (ev.target as Element).closest('[data-node]');
      const id = g?.getAttribute('data-node');
      if (!id) return;
      this.card.textContent = '…';
      void api
        .puzzle(id)
        .then((p) => {
          this.card.textContent = p.markdown;
        })
        .catch((e) => {
          this.card.textContent = (e as Error).message;
        });
    });
    this.svgBox = box;
    this.restyle();
    return box;
  }

  /** Applies the critical-path and heat toggles to the drawn graph (no round trip). */
  private restyle() {
    const box = this.svgBox,
      p = this.p;
    if (!box || !p) return;
    const heat: Record<string, number> =
      this.heatSource === 'playtests' ? { ...(this.pt?.report.heat ?? {}) } : { ...(this.s?.profile?.perAction ?? {}) };
    if (this.heatSource !== 'playtests')
      for (const [room, n] of Object.entries(this.s?.profile?.perRoom ?? {})) heat[`room:${room}`] = n;
    const max = Math.max(1, ...Object.values(heat));
    for (const g of box.querySelectorAll<SVGGElement>('g[data-node]')) {
      const id = g.dataset.node!;
      const rect = g.querySelector('rect');
      if (!rect) continue;
      if (!rect.dataset.fill) rect.dataset.fill = rect.getAttribute('fill') ?? '';
      g.style.opacity = this.focus && p.classes[id] !== 'critical' ? '0.22' : '';
      const n = heat[id];
      rect.setAttribute(
        'fill',
        this.heat && n !== undefined ? heatFill(Math.log1p(n) / Math.log1p(max)) : rect.dataset.fill,
      );
    }
    for (const path of box.querySelectorAll<SVGPathElement>('path[marker-end]'))
      path.style.opacity = this.focus ? '0.35' : '';
  }

  /** What the solver measured: the cost of the search and what makes the states, with the warnings a designer acts on. */
  private health(P: SolveProfile): HTMLElement {
    const warns: string[] = [];
    for (const g of P.independent)
      warns.push(
        `${g.dims.join(', ')} evolve independently (${g.combos} of ${g.product} combinations seen): a checkpoint between them would cut the states`,
      );
    for (const [room, f] of Object.entries(P.fallbackByRoom))
      if (f.candidates >= 40 && f.fallback / f.candidates >= 0.9)
        warns.push(
          `${room}: ${f.candidates} use/give combinations, ${f.rules} answered by a rule (the rest is skipped statically)`,
        );
    if (P.branching.worst && P.branching.max >= 60)
      warns.push(
        `${P.branching.worst.room} offers ${P.branching.max} actions to try with ${P.branching.worst.inventory.length} items in the bag; ${P.branching.worst.effective} changed something`,
      );
    const dims = P.dims.filter((d) => d.split > 0).slice(0, 8);
    return h(
      'details',
      { class: 'health', open: true },
      h(
        'summary',
        null,
        'Solver health ',
        h(
          'span',
          { class: 'muted small' },
          `${P.tries} runs · ${P.skipped} actions skipped · ${P.noops} no-ops · queue ${P.maxQueue} · ${P.branching.avg.toFixed(0)} actions per state`,
        ),
      ),
      warns.length
        ? h(
            'ul',
            { class: 'msgs warnings' },
            warns.map((w) => h('li', null, w)),
          )
        : h('p', { class: 'muted small' }, 'No independent branches, no room with runaway branching.'),
      dims.length
        ? h(
            'table',
            { class: 'dims' },
            h(
              'tr',
              null,
              h('th', null, 'splits the states'),
              h('th', null, 'merged without it'),
              h('th', null, 'values'),
            ),
            dims.map((d) =>
              h('tr', null, h('td', null, d.key), h('td', null, String(d.split)), h('td', null, String(d.values))),
            ),
          )
        : null,
      h(
        'p',
        { class: 'muted small' },
        `Monotonic: ${P.monotonic.flags.length} flags, ${P.monotonic.items.length} items never lost once gained.`,
      ),
      h('details', null, h('summary', null, 'Full profile'), h('pre', { class: 'md' }, profileText(P))),
    );
  }

  private async screenshot() {
    this.shot.replaceChildren(h('p', { class: 'muted' }, 'Rendering…'));
    try {
      const r = await api.screenshot(this.shotRoom, this.shotCp);
      this.shot.replaceChildren(
        h('img', { src: r.url, alt: `${this.shotRoom} screenshot` }),
        h('p', { class: 'muted small' }, r.file),
      );
    } catch (e) {
      this.shot.replaceChildren(h('p', { class: 'error' }, (e as Error).message));
      toast((e as Error).message, 'error');
    }
  }
}
