// npm run i18n -- extract [--lang <xx>] | status
// extract: writes games/<id>/locales/<lang>.json with every text of the game (path → text). With no --lang, the base
// language (game.lang, else "en"): the reference file. With --lang xx: creates or updates the translation file, keeping
// what is translated and adding the missing paths with the base text (to translate). status: coverage of every file.
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { localeStatus, textPaths } from '../src/engine/tools/i18n';
import { GAME, GAME_DIR, loadGameModule } from './game';

const { game } = await loadGameModule();
const args = process.argv.slice(2);
const cmd = args[0] ?? 'status';
const li = args.indexOf('--lang');
const lang = li >= 0 ? args[li + 1] : undefined;
const base = game.lang ?? 'en';
const dir = join(GAME_DIR, 'locales');
const file = (l: string) => join(dir, `${l}.json`);
const read = (l: string): Record<string, string> => { try { return JSON.parse(readFileSync(file(l), 'utf8')); } catch { return {}; } };

if (cmd === 'extract') {
  mkdirSync(dir, { recursive: true });
  const paths = textPaths(game);
  const target = lang ?? base;
  const existing = target === base ? {} : read(target);
  const out: Record<string, string> = { _: `${game.title} — texts in "${target}"${target === base ? ' (as written: the reference)' : ` (translate the values; missing ones were filled with the ${base} text)`}, paths generated by npm run i18n` };
  let added = 0;
  for (const { path, text } of paths) { if (existing[path]) out[path] = existing[path]; else { out[path] = text; added++; } }
  writeFileSync(file(target), JSON.stringify(out, null, 1) + '\n');
  console.log(`${file(target)}: ${paths.length} texts${target === base ? '' : `, ${added} to translate`}`);
  process.exit(0);
}

if (cmd === 'status') {
  const langs = existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith('.json')).map((f) => f.slice(0, -5)) : [];
  if (!langs.length) { console.log(`[${GAME}] no locales (npm run i18n -- extract --lang <xx>)`); process.exit(0); }
  let bad = 0;
  for (const l of langs) {
    const st = localeStatus(game, read(l));
    const ok = st.missing.length === 0 && st.stale.length === 0;
    if (!ok) bad++;
    console.log(`${ok ? '✔' : '…'}  ${l}: ${st.translated}/${st.total} translated${st.missing.length ? `, ${st.missing.length} missing` : ''}${st.stale.length ? `, ${st.stale.length} stale` : ''}${st.long.length ? `, ${st.long.length} long` : ''}`);
    for (const m of st.missing.slice(0, 10)) console.log(`     missing ${m}`);
    for (const m of st.stale.slice(0, 10)) console.log(`     stale   ${m}`);
  }
  process.exit(0);
}
console.log('usage: npm run i18n -- extract [--lang <xx>] | status');
process.exit(1);
