// npm run i18n -- extract [--lang <xx>] | status | voices
// extract: writes games/<id>/locales/<lang>.json with every text of the game (path → text). With no --lang, the base
// language (game.lang, else "en"): the reference file. With --lang xx: creates or updates the translation file, keeping
// what is translated, following texts that moved (a reordered list: same source text in the previous reference file),
// parking what disappeared under `_stale:<path>`, and adding the missing paths with the base text (to translate).
// The reference file is refreshed at the same time. status: coverage of every file.
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { localeStatus, mergeLocale, textPaths } from '../src/engine/tools/i18n';
import { GAME, GAME_DIR, loadGameModule } from './game';
import { uiFallbacks } from '../src/engine/dom/ui-defaults';
import { lineIds } from '../src/engine/core/content-ids';

const { game } = await loadGameModule();
const args = process.argv.slice(2);
const cmd = args[0] ?? 'status';
const li = args.indexOf('--lang');
const lang = li >= 0 ? args[li + 1] : undefined;
const base = game.lang ?? 'en';
const dir = join(GAME_DIR, 'locales');
const file = (l: string) => join(dir, `${l}.json`);
const read = (l: string): Record<string, string> => { try { return JSON.parse(readFileSync(file(l), 'utf8')); } catch { return {}; } };

if (cmd === 'extract') {
  mkdirSync(dir, { recursive: true });
  const paths = textPaths(game);
  const target = lang ?? base;
  const header = (l: string) => `${game.title} — texts in "${l}"${l === base ? ' (as written: the reference)' : ` (translate the values; missing ones were filled with the ${base} text; _stale: entries no longer match anything)`}, paths generated by npm run i18n`;
  const reference: Record<string, string> = { _: header(base) };
  for (const { path, text } of paths) reference[path] = text;
  if (target === base) {
    writeFileSync(file(base), JSON.stringify(reference, null, 1) + '\n');
    console.log(`${file(base)}: ${paths.length} texts`);
    process.exit(0);
  }
  const m = mergeLocale(paths, read(target), read(base));
  writeFileSync(file(target), JSON.stringify({ _: header(target), ...m.table }, null, 1) + '\n');
  writeFileSync(file(base), JSON.stringify(reference, null, 1) + '\n');
  console.log(`${file(target)}: ${paths.length} texts, ${m.added} to translate${m.remapped ? `, ${m.remapped} followed a moved text` : ''}${m.revived ? `, ${m.revived} revived` : ''}${m.stale.length ? `, ${m.stale.length} parked as _stale` : ''}`);
  process.exit(0);
}

if (cmd === 'voices') {
  // The voice production table: every line with a stable id, whether `audio.voices` has a clip under it, and the
  // clips no line claims. Lines without an id are not listed: `npm run ids -- --lines` first.
  const lines = lineIds(game);
  const clips = game.audio?.voices ?? {};
  const missing = lines.filter((l) => !clips[l.id]);
  const orphans = Object.keys(clips).filter((k) => !lines.some((l) => l.id === k));
  console.log(`[${GAME}] ${lines.length} line(s) with an id, ${lines.length - missing.length} voiced, ${missing.length} without a clip, ${orphans.length} clip(s) no line claims`);
  for (const l of missing.slice(0, 200)) console.log(`  ${l.id.padEnd(48)} ${l.who}: ${l.text.length > 60 ? l.text.slice(0, 60) + '…' : l.text}`);
  for (const k of orphans) console.log(`  orphan clip ${k} → ${clips[k]}`);
  process.exit(0);
}

if (cmd === 'status') {
  const langs = existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith('.json')).map((f) => f.slice(0, -5)) : [];
  if (!langs.length) { console.log(`[${GAME}] no locales (npm run i18n -- extract --lang <xx>)`); process.exit(0); }
  let bad = 0;
  for (const l of langs) {
    const st = localeStatus(game, read(l));
    // Identical to the source without being listed in `i18n.same`: an untranslated line, not a choice.
    const ok = st.missing.length === 0 && st.stale.length === 0 && (l === base || st.untranslated.length === 0);
    if (!ok) bad++;
    console.log(`${ok ? '✔' : '…'}  ${l}: ${st.translated}/${st.total} translated${st.missing.length ? `, ${st.missing.length} missing` : ''}${st.stale.length ? `, ${st.stale.length} stale` : ''}${st.long.length ? `, ${st.long.length} long` : ''}${st.same.length && l !== base ? `, ${st.same.length} same as ${base}${st.untranslated.length ? ` (${st.untranslated.length} not in i18n.same)` : ', all listed in i18n.same'}` : ''}`);
    for (const m of st.missing.slice(0, 10)) console.log(`     missing ${m}`);
    for (const m of st.stale.slice(0, 10)) console.log(`     stale   ${m}`);
    if (l !== base) for (const m of st.untranslated.slice(0, 20)) console.log(`     same    ${m}   (translate it, or list it in i18n.same)`);
  }
  const fb = Object.keys(uiFallbacks(game.ui));
  if (fb.length) console.log(`ℹ  ${fb.length} ui key(s) left to the English defaults (a player sees them in English in every language): ${fb.join(', ')}`);
  process.exit(bad ? 1 : 0);
}
console.log('usage: npm run i18n -- extract [--lang <xx>] | status | voices');
process.exit(1);
