// npm run test:mutation:core [-- --set=core|reality|all] [--file=src/engine/core/cond.ts] [--fresh] [--hash] (4.1.0 "Clarity",
// lot G; the sets and the gate by identity since 4.1.2): mutation testing of what a save, a session, a condition and
// a migration rest on (`core`), and of what a signal from the world outside rests on (`reality`: the engine's
// receive, the protocol, the client, the Bridge, its store, its lock and its policy). Each mutant changes one thing
// in the source (a comparison flipped, `&&` for `||`, a negation dropped, a condition forced, a boolean inverted),
// the tests that judge that set run against it (vitest.mutation.config.ts, `MUTATION_SET`), and the mutant must
// make one of them fail. A mutant that survives is a missing test, or an equivalent mutant: docs/dev/mutants.json
// names each one (file, operator, from, to) with its reason, docs/dev/MUTANTS.md explains them, and any survivor
// not named there fails the run, whatever the count. The source file is restored after each mutant, and on exit. (Stryker 10 does not activate its mutants under Vitest 5 here: 739 of 749
// survived, a block emptied included; this tool runs each mutant as plain source.)
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import ts from 'typescript';
import { ROOT } from './game';
import { SETS, setsOf, TESTS, type MutationSet } from './mutation-sets';

export { SETS, type MutationSet };
export const TARGETS = SETS.core;

/**
 * The hash of everything a run's verdict depends on (4.1.8): the set's sources and tests, the two configurations,
 * this tool, the named survivors, the lockfile. A report whose `inputHash` is the current one says what a new run
 * would say: the release reuses it instead of running the set again (`--reuse`, the default; `--fresh` runs anyway).
 * A commit that changes none of these (docs, a release's version) keeps the hash, so the key is not the commit.
 */
export function inputHash(set: MutationSet | 'all'): string {
  const files = new Set<string>([
    'tools/mutate.ts',
    'tools/mutation-sets.ts',
    'vitest.mutation.config.ts',
    'vite.config.ts',
    'docs/dev/mutants.json',
    'package-lock.json',
  ]);
  for (const k of setsOf(set)) {
    for (const f of SETS[k]) files.add(f);
    for (const g of TESTS[k]) for (const f of expand(g)) files.add(f);
  }
  const h = createHash('sha256');
  for (const f of [...files].sort()) {
    h.update(f);
    h.update('\0');
    h.update(existsSync(resolve(ROOT, f)) ? readFileSync(resolve(ROOT, f)) : 'missing');
    h.update('\0');
  }
  return h.digest('hex').slice(0, 16);
}

/** The files a vitest `include` glob of the form `dir/prefix-*.test.ts` names (one `*`, in the file name). */
function expand(glob: string): string[] {
  if (!glob.includes('*')) return [glob];
  const dir = dirname(glob);
  const re = new RegExp(
    `^${glob
      .slice(dir.length + 1)
      .replace(/[.+?^${}()|[\]\\]/g, '\\$&')
      .replace(/\*/g, '.*')}$`,
  );
  return readdirSync(resolve(ROOT, dir))
    .filter((f) => re.test(f))
    .map((f) => `${dir}/${f}`)
    .sort();
}

/** What a run writes (4.1.8): the set, its input hash, the commit, the verdict, and every mutant's fate. */
export interface MutationReport {
  v: 1;
  set: MutationSet | 'all' | 'file';
  inputHash: string;
  commitSha: string;
  at: string;
  status: 'passed' | 'failed';
  killed: number;
  total: number;
  results: (Omit<Mutant, 'start' | 'end'> & { status: string })[];
}

/** The named survivors as a Markdown table, what `--doc` writes into docs/dev/MUTANTS.md between its markers. */
export function survivorsTable(known: KnownSurvivor[]): string {
  const rows = [...known]
    .sort((a, b) => a.file.localeCompare(b.file) || a.from.localeCompare(b.from))
    .map(
      (k) =>
        `| \`${k.file}\`${k.context ? ` (\`${k.context.replace(/\|/g, '\\|')}\`)` : ''} | \`${k.operator}\`: \`${k.from}\` → \`${k.to}\` | ${k.why} |`,
    );
  return `| Where | Mutant | Why it is equivalent |\n|---|---|---|\n${rows.join('\n')}\n`;
}
export const DOC_MARKERS = ['<!-- mutants:start -->', '<!-- mutants:end -->'] as const;
/** MUTANTS.md with the table of docs/dev/mutants.json between its markers (the text outside them is the author's). */
export function withSurvivorsTable(doc: string, known: KnownSurvivor[]): string {
  const [a, b] = DOC_MARKERS;
  const i = doc.indexOf(a);
  const j = doc.indexOf(b);
  if (i < 0 || j < 0 || j < i) throw new Error(`MUTANTS.md: the markers ${a} … ${b} are missing`);
  return `${doc.slice(0, i + a.length)}\n${known.length} named in \`docs/dev/mutants.json\` (generated by \`npm run test:mutation:core -- --doc\`; the gate reads the JSON, this table says it):\n\n${survivorsTable(known)}${doc.slice(j)}`;
}

const commitSha = () => {
  try {
    return execFileSync('git', ['rev-parse', 'HEAD'], { cwd: ROOT, encoding: 'utf8' }).trim();
  } catch {
    return 'unknown';
  }
};

/** A report of this set with the current input hash, if one is there. */
export function reusableReport(set: MutationSet | 'all', hash: string): MutationReport | null {
  const file = resolve(ROOT, `.cache/mutation/report-${set}.json`);
  if (!existsSync(file)) return null;
  try {
    const r = JSON.parse(readFileSync(file, 'utf8')) as Partial<MutationReport>;
    return r.v === 1 && r.inputHash === hash && r.status === 'passed' && Array.isArray(r.results)
      ? (r as MutationReport)
      : null;
  } catch {
    return null;
  }
}

/** An equivalent mutant, as docs/dev/mutants.json names it: the line may move, the edit itself may not. */
export interface KnownSurvivor {
  file: string;
  operator: string;
  from: string;
  to: string;
  why: string;
  /**
   * The source line the mutant sits on, trimmed (4.1.8): without it an entry names every mutant of that file with the
   * same edit (`+` → `-` anywhere), and a new survivor on another line would hide behind an old equivalent.
   */
  context?: string;
}
export const sameMutant = (a: Pick<Mutant, 'file' | 'operator' | 'from' | 'to' | 'context'>, b: KnownSurvivor) =>
  a.file === b.file &&
  a.operator === b.operator &&
  a.from === b.from &&
  a.to === b.to &&
  (b.context === undefined || a.context === b.context);

export interface Mutant {
  file: string;
  line: number;
  /** The source line, trimmed. */
  context: string;
  operator: string;
  from: string;
  to: string;
  start: number;
  end: number;
}

const SWAP: Partial<Record<ts.SyntaxKind, [ts.SyntaxKind, string]>> = {
  [ts.SyntaxKind.EqualsEqualsEqualsToken]: [ts.SyntaxKind.ExclamationEqualsEqualsToken, '!=='],
  [ts.SyntaxKind.ExclamationEqualsEqualsToken]: [ts.SyntaxKind.EqualsEqualsEqualsToken, '==='],
  [ts.SyntaxKind.LessThanToken]: [ts.SyntaxKind.LessThanEqualsToken, '<='],
  [ts.SyntaxKind.LessThanEqualsToken]: [ts.SyntaxKind.LessThanToken, '<'],
  [ts.SyntaxKind.GreaterThanToken]: [ts.SyntaxKind.GreaterThanEqualsToken, '>='],
  [ts.SyntaxKind.GreaterThanEqualsToken]: [ts.SyntaxKind.GreaterThanToken, '>'],
  [ts.SyntaxKind.AmpersandAmpersandToken]: [ts.SyntaxKind.BarBarToken, '||'],
  [ts.SyntaxKind.BarBarToken]: [ts.SyntaxKind.AmpersandAmpersandToken, '&&'],
  [ts.SyntaxKind.PlusToken]: [ts.SyntaxKind.MinusToken, '-'],
  [ts.SyntaxKind.MinusToken]: [ts.SyntaxKind.PlusToken, '+'],
};

/** Every mutant of a source file, in order. Pure: reads the text, returns the edits. */
export function mutants(file: string, src: string): Mutant[] {
  const sf = ts.createSourceFile(file, src, ts.ScriptTarget.Latest, true);
  const out: Mutant[] = [];
  const lines = src.split('\n');
  const line = (pos: number) => sf.getLineAndCharacterOfPosition(pos).line + 1;
  const add = (operator: string, node: ts.Node, to: string, start = node.getStart(sf), end = node.getEnd()) => {
    const n = line(start);
    out.push({
      file,
      line: n,
      context: (lines[n - 1] ?? '').trim(),
      operator,
      from: src.slice(start, end),
      to,
      start,
      end,
    });
  };
  const visit = (n: ts.Node) => {
    // Types, imports and comments carry no behaviour.
    if (ts.isTypeNode(n) || ts.isImportDeclaration(n) || ts.isInterfaceDeclaration(n) || ts.isTypeAliasDeclaration(n))
      return;
    if (ts.isBinaryExpression(n)) {
      const swap = SWAP[n.operatorToken.kind];
      if (swap) add('operator', n.operatorToken, swap[1]);
    }
    if (ts.isPrefixUnaryExpression(n) && n.operator === ts.SyntaxKind.ExclamationToken)
      add('negation', n, n.operand.getText(sf));
    if (n.kind === ts.SyntaxKind.TrueKeyword) add('boolean', n, 'false');
    if (n.kind === ts.SyntaxKind.FalseKeyword) add('boolean', n, 'true');
    if (ts.isIfStatement(n) || ts.isConditionalExpression(n)) {
      const c = ts.isIfStatement(n) ? n.expression : n.condition;
      add('condition true', c, 'true');
      add('condition false', c, 'false');
    }
    ts.forEachChild(n, visit);
  };
  visit(sf);
  return out;
}

export const apply = (src: string, m: Mutant) => src.slice(0, m.start) + m.to + src.slice(m.end);

function runTests(set: MutationSet | 'all'): 'killed' | 'survived' | 'timeout' {
  try {
    execFileSync('npx', ['vitest', 'run', '--config', 'vitest.mutation.config.ts', '--bail', '1'], {
      cwd: ROOT,
      stdio: 'ignore',
      timeout: 180_000,
      env: { ...process.env, MUTATION_SET: set },
    });
    return 'survived';
  } catch (e) {
    return (e as { signal?: string }).signal === 'SIGTERM' ? 'timeout' : 'killed';
  }
}

if (process.argv[1]?.endsWith('mutate.ts')) {
  const only = process.argv.find((a) => a.startsWith('--file='))?.split('=')[1];
  const setArg = (process.argv.find((a) => a.startsWith('--set='))?.split('=')[1] ?? 'core') as MutationSet | 'all';
  const setOf = (f: string): MutationSet | 'all' =>
    (Object.keys(SETS) as MutationSet[]).find((k) => SETS[k].includes(f)) ?? 'all';
  const set: MutationSet | 'all' = only ? setOf(only) : setArg;
  const files = only ? [only] : setsOf(set).flatMap((k) => SETS[k]);
  if (process.argv.includes('--doc')) {
    const known = JSON.parse(readFileSync(resolve(ROOT, 'docs/dev/mutants.json'), 'utf8')) as KnownSurvivor[];
    const doc = resolve(ROOT, 'docs/dev/MUTANTS.md');
    writeFileSync(doc, withSurvivorsTable(readFileSync(doc, 'utf8'), known));
    console.log(`✔  docs/dev/MUTANTS.md: ${known.length} named survivors written`);
    process.exit(0);
  }
  const hash = inputHash(set);
  if (process.argv.includes('--hash')) {
    console.log(hash);
    process.exit(0);
  }
  // A report of these very inputs says what this run would say (4.1.8): reused, unless --fresh.
  if (!only && !process.argv.includes('--fresh')) {
    const r = reusableReport(set, hash);
    if (r) {
      console.log(
        `✔  ${r.killed}/${r.total} mutants killed (set ${set}, inputs ${hash}, measured on ${r.commitSha.slice(0, 7)} at ${r.at}): the same inputs, the report reused (--fresh runs again)`,
      );
      process.exit(0);
    }
  }
  const originals = new Map(files.map((f) => [f, readFileSync(resolve(ROOT, f), 'utf8')]));
  const restore = () => {
    for (const [f, s] of originals) writeFileSync(resolve(ROOT, f), s);
  };
  process.on('SIGINT', () => {
    restore();
    process.exit(130);
  });
  if (runTests(set) !== 'survived') {
    console.error('✖  the tests fail before any mutation: fix them first');
    process.exit(2);
  }
  const results: (Mutant & { status: string })[] = [];
  try {
    for (const f of files) {
      const src = originals.get(f)!;
      const ms = mutants(f, src);
      console.log(`${f}: ${ms.length} mutants`);
      for (const m of ms) {
        writeFileSync(resolve(ROOT, f), apply(src, m));
        const status = runTests(set);
        results.push({ ...m, status });
        if (status === 'survived') console.log(`  survived ${f}:${m.line} ${m.operator}: ${m.from} → ${m.to}`);
      }
      writeFileSync(resolve(ROOT, f), src);
    }
  } finally {
    restore();
  }
  const killed = results.filter((r) => r.status !== 'survived').length;
  const out = resolve(ROOT, '.cache/mutation');
  if (!existsSync(out)) mkdirSync(out, { recursive: true });
  for (const f of files) {
    const rs = results.filter((r) => r.file === f);
    const k = rs.filter((r) => r.status !== 'survived').length;
    console.log(`  ${f}: ${k}/${rs.length} killed (${rs.length ? ((100 * k) / rs.length).toFixed(1) : '100'}%)`);
  }
  // The equivalent mutants, each named in docs/dev/mutants.json (and explained in MUTANTS.md): a survivor not named
  // there fails the run, in every mode, whatever the count; a name whose mutant no longer exists is reported too.
  const known = JSON.parse(readFileSync(resolve(ROOT, 'docs/dev/mutants.json'), 'utf8')) as KnownSurvivor[];
  const survivors = results.filter((r) => r.status === 'survived');
  const unexplained = survivors.filter((r) => !known.some((k) => sameMutant(r, k)));
  const stale = known.filter((k) => files.includes(k.file) && !survivors.some((r) => sameMutant(r, k)));
  for (const r of unexplained)
    console.log(
      `  ✖ not in docs/dev/mutants.json: ${r.file}:${r.line} ${r.operator}: ${r.from} → ${r.to}  (${r.context})`,
    );
  for (const k of stale)
    console.log(`  ⚠ named in docs/dev/mutants.json but killed or gone: ${k.file} ${k.operator}: ${k.from} → ${k.to}`);
  const report: MutationReport = {
    v: 1,
    set: only ? 'file' : set,
    inputHash: hash,
    commitSha: commitSha(),
    at: new Date().toISOString(),
    status: unexplained.length ? 'failed' : 'passed',
    killed,
    total: results.length,
    results: results.map(({ start, end, ...r }) => r),
  };
  writeFileSync(resolve(out, `report-${report.set}.json`), JSON.stringify(report, null, 1));
  console.log(
    `${unexplained.length ? '✖' : '✔'}  ${killed}/${results.length} mutants killed, ${survivors.length - unexplained.length} survivors explained, ${unexplained.length} not; report in .cache/mutation/report-${report.set}.json (inputs ${hash})`,
  );
  if (unexplained.length) process.exitCode = 1;
}
