"""Takes the mouths generated by an image generator and pastes them back onto the VALIDATED sprite.
Only the area that changed (mouth, eyes) is reused; everything else in the sprite stays pixel for pixel.

python3 tools/talk-apply.py <char>_<pose>        (reads games/<id>/private/talk_kits/<name>.png|.json
                                                    and games/<id>/private/talk_kits/<name>_chatgpt.png or _out.png)
-> games/<id>/art/talk_<char>/<pose>/t1.png ... t6.png   (t1 = the validated sprite itself)
"""
import sys, os, json, numpy as np, cv2
from PIL import Image
from scipy import ndimage

GAME = os.environ.get('GAME') or json.load(open('package.json')).get('config', {}).get('game', 'demo')
X, K = f'games/{GAME}/art', f'games/{GAME}/private/talk_kits'
name = sys.argv[1]
meta = json.load(open(f'{K}/{name}.json'))
kit = np.asarray(Image.open(f'{K}/{name}.png').convert('RGB')).astype(np.float32)
res_p = f'{K}/{name}_chatgpt.png' if os.path.exists(f'{K}/{name}_chatgpt.png') else f'{K}/{name}_out.png'
res_img = Image.open(res_p).convert('RGB')
if res_img.size != (1536, 1024): res_img = res_img.resize((1536, 1024), Image.LANCZOS)
res = np.asarray(res_img).astype(np.float32)
C, (ox, oy), (bw, bh), s = meta['cell'], meta['offset'], meta['size'], meta['scale']
sprite = np.asarray(Image.open(f"{X}/{meta['sprite']}.png").convert('RGBA')).astype(np.float32)
x0, y0, x1, y1 = meta['box']
ref = kit[oy:oy + bh, ox:ox + bw]                         # the original head, enlarged
head_mask = np.asarray(Image.fromarray(sprite[y0:y1, x0:x1, 3].astype(np.uint8)).resize((bw, bh), Image.LANCZOS)) > 128
g_ref = cv2.cvtColor(ref.astype(np.uint8), cv2.COLOR_RGB2GRAY).astype(np.float32)

def ecc(tmpl, img, mode=cv2.MOTION_AFFINE):
    """Transform that brings `img` onto `tmpl` (both in grayscale)."""
    warp = np.eye(2, 3, dtype=np.float32)
    try:
        _, warp = cv2.findTransformECC(tmpl, img, warp, mode, (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 300, 1e-6), None, 5)
    except cv2.error:
        (dx, dy), _ = cv2.phaseCorrelate(tmpl, img); warp = np.float32([[1, 0, dx], [0, 1, dy]])
    return warp
gray = lambda x: cv2.cvtColor(x.astype(np.uint8), cv2.COLOR_RGB2GRAY).astype(np.float32)
raw = []
for k in range(6):
    cx, cy = (k % 3) * C, (k // 3) * C
    raw.append(res[cy:cy + C, cx:cx + C])            # the full cell from the reply
# 1) each cell is aligned on cell 1 of the reply (same style: precise alignment)
g1 = gray(raw[0])
same = [raw[0]] + [cv2.warpAffine(raw[k], ecc(g1, gray(raw[k])), (C, C), flags=cv2.INTER_LINEAR + cv2.WARP_INVERSE_MAP,
                                  borderMode=cv2.BORDER_REPLICATE) for k in range(1, 6)]
# 2) cell 1 is aligned on the kit's original head; the same transform applies to all cells
kit_cell = kit[0:C, 0:C]
W = ecc(gray(kit_cell), g1)
cells = [cv2.warpAffine(x, W, (C, C), flags=cv2.INTER_LINEAR + cv2.WARP_INVERSE_MAP, borderMode=cv2.BORDER_REPLICATE)[oy:oy + bh, ox:ox + bw]
         for x in same]
base_cell = cells[0]                                      # cell 1 of the reply: mouth closed, used as the reference
out = f"{X}/talk_{name.split('_')[0]}/{name.split('_', 1)[1]}"
os.makedirs(out, exist_ok=True)
Image.fromarray(sprite.astype(np.uint8), 'RGBA').save(f'{out}/t1.png')
lab_ref = cv2.cvtColor(ref.astype(np.uint8), cv2.COLOR_RGB2LAB).astype(np.float32)
for k in range(1, 6):
    cell = cells[k]
    diff = np.abs(cell - base_cell).mean(-1)
    ch = (diff > 22) & head_mask
    ch = ndimage.binary_opening(ch, iterations=2)
    lab, n = ndimage.label(ndimage.binary_dilation(ch, iterations=4))
    keep = []
    for i, sl in enumerate(ndimage.find_objects(lab), start=1):
        area = (ch & (lab == i)).sum(); h = sl[0].stop - sl[0].start; w = sl[1].stop - sl[1].start
        if area > 30 and h < bh * 0.35 and w < bw * 0.45: keep.append(i)   # mouth, eyes: compact blobs
    ch = np.isin(lab, keep)
    if ch.sum() > 0.12 * head_mask.sum():             # too large: keep only the 2 biggest blobs (mouth, eyes)
        lab2, n2 = ndimage.label(ch); sz = ndimage.sum(ch, lab2, range(1, n2 + 1))
        ch = np.isin(lab2, list(np.argsort(sz)[-2:] + 1))
    ch = ndimage.binary_dilation(ch, iterations=6) & head_mask
    # color: match the cell to the original head around the changed area (a ring)
    ring = ndimage.binary_dilation(ch, iterations=12) & ~ch & head_mask
    lab_c = cv2.cvtColor(cell.astype(np.uint8), cv2.COLOR_RGB2LAB).astype(np.float32)
    if ring.sum() > 50:
        for c in range(3):
            a_, b_ = lab_c[..., c][ring], lab_ref[..., c][ring]
            lab_c[..., c] = (lab_c[..., c] - a_.mean()) / (a_.std() + 1) * (b_.std() + 1) + b_.mean()
    cell = cv2.cvtColor(np.clip(lab_c, 0, 255).astype(np.uint8), cv2.COLOR_LAB2RGB).astype(np.float32)
    soft = cv2.GaussianBlur(ch.astype(np.float32), (0, 0), 3)
    patch = ref * (1 - soft[..., None]) + cell * soft[..., None]
    # back to the sprite's own size, and pasted into the head's box
    small = np.asarray(Image.fromarray(patch.clip(0, 255).astype(np.uint8)).resize((x1 - x0, y1 - y0), Image.LANCZOS)).astype(np.float32)
    soft_s = np.asarray(Image.fromarray((soft * 255).astype(np.uint8)).resize((x1 - x0, y1 - y0), Image.LANCZOS)).astype(np.float32) / 255
    soft_s *= sprite[y0:y1, x0:x1, 3] / 255
    out_img = sprite.copy()
    out_img[y0:y1, x0:x1, :3] = sprite[y0:y1, x0:x1, :3] * (1 - soft_s[..., None]) + small * soft_s[..., None]
    Image.fromarray(out_img.clip(0, 255).astype(np.uint8), 'RGBA').save(f'{out}/t{k + 1}.png')
    print(f't{k + 1}: repainted area {int(ch.sum())} px')
print('ok', out)
