import { defineRoom } from '@engine/core/define';

// Room 1: Grandma's house. Tutorial (in game.ts, start.intro), the armchair, and the finale at the pantry.
export default defineRoom({
  id: 'house',
  music: 'theme',
  name: 'Grandma\'s house',
  decor: 'decor/dining',
  description: 'Grandma\'s dining room at golden hour, seen from the front. Left: a tall wooden bookshelf with books, plants and a vase, a lamp with an orange shade on a small side table. Center: wide-open French windows with flowered curtains, giving on to a sunny garden, a village and a church spire. Right: a white door to the hall, family pictures on green damask wallpaper. Terracotta tiled floor with a big red rug. Warm, cozy, late-afternoon sun',

  props: {
    pantry: { name: 'pantry cupboard', states: { locked: 'home2/r1c3', open: 'home2/r1c4' }, initial: 'locked',
      // A prop animation with a frame event: the door jumps, the latch clicks on frame 1 (`{ play: ['pantry', 'rattle'] }`).
      anims: { rattle: { frames: ['home2/r1c4', 'home2/r1c3', 'home2/r1c4', 'home2/r1c3'], fps: 12, at: { 1: [{ sfx: 'latch' }] } } } },
    // Once Grandpa is home (game.ts `events`), he sits here: his seated sheet brings its own armchair.
    armchair: { name: 'Grandpa\'s armchair', states: { remote: 'home2/r2c1', searched: 'home2/r2c2' }, initial: 'remote', visible: { not: { actorIn: ['grandpa', 'house'] } } },
    clock: { name: 'clock', img: 'home2/r1c5' },
    table: { img: 'furniture_dining/table' },
    chair: { img: 'furniture_dining/chaise2' },
    shell: { name: 'shell phone', img: 'items/r4c3', visible: { not: { has: 'shell_phone' } } },
    teacup: { name: 'teacup', img: 'home2/r2c3' },
  },

  actors: {
    grandma: { char: 'grandma', facing: 'right' },
    biscuit: { char: 'biscuit', pose: 'sleep' },
    // A moving character (cast.ts `room: 'garden'`): hidden here until `moveActor` brings him home.
    grandpa: { char: 'grandpa', facing: 'left' },
  },

  hotspots: {
    door: { name: 'hall door' },
    bookshelf: { name: 'bookshelf' },
    lamp: { name: 'lamp' },
  },

  // A declared exit: a hotspot (placed in the layout like any zone) plus the rule that takes it, generated by the engine.
  exits: {
    window: { name: 'garden window', to: 'garden', entry: 'house', if: { unlocked: 'garden' }, locked: 'Not yet. First, the key. Grandma knows things.', sfx: 'door_open', verbs: ['use', 'open', 'push'] },
  },

  look: {
    pantry: ['The pantry cupboard. The sardines live in there.', 'Locked. I can hear the sardines. (Sardines are silent. I hear them anyway.)',
      'Still locked. Still sardines.', 'I could stare at it all day. I might.'],
    armchair: ['Grandpa\'s armchair. It eats remotes, coins and socks.', 'Something shiny behind the cushion?'],
    clock: ['Tick. Tock. Breakfast o\'clock.', 'Two hours past breakfast, actually.', 'The clock agrees with me: food.'],
    shell: 'Grandma\'s shell phone. Talk into it and Grandma answers. From anywhere.',
    teacup: ['Grandma\'s tea. Lukewarm.', 'Not sardine-flavoured. Pass.'],
    grandma: ['Grandma. Keeper of sardines. Loser of keys.', 'She smells of tea and biscuits. Not Biscuit the cat. The other kind.'],
    biscuit: ['Biscuit. My big brother. Sleeps twenty hours a day.', 'The other four hours, he naps.'],
    grandpa: ['Grandpa. He came home for the sardines. With his armchair.', 'He is "guarding the pantry". With his eyes closed.'],
    hero: ['Pixel. Smaller than me. Faster than me. Fine.', 'My little brother. Still planning. Always planning.'],
    window: ['The garden. Grandpa is out there somewhere.', 'Fresh air, birds, flowers. And Grandpa.'],
    door: 'The hall. Nothing to eat there. I checked. Twice.',
    bookshelf: ['Books. Not one about sardines. Disappointing.', 'A cookbook! ...Vegetables. Never mind.'],
    lamp: 'A warm lamp. Good for naps. Everything is good for naps.',
  },

  on: [
    // Tutorial step 3, and the hint item.
    { id: 'house.take-shell', verb: 'take', a: 'shell', do: [{ gain: 'shell_phone' }, { sfx: 'select' }, { say: ['hero', 'Got it. It smells like the sea.'], id: 'house.take-shell.l-got-it-it-smells' }] },

    // The armchair: a token behind the cushion, once (the prop state remembers it).
    { id: 'house.open-armchair', verb: ['open', 'pull', 'push', 'use'], a: 'armchair', if: { all: [{ player: 'hero' }, { prop: ['armchair', 'remote'] }] }, do: [
      { sfx: 'cloth' }, { prop: ['armchair', 'searched'] }, { say: ['hero', 'Behind the cushion... a market token!'], id: 'house.open-armchair.l-behind-the' }, { gain: 'token' },
      { say: ['hero', 'And Grandpa\'s remote. I will leave that one. Too much TV.'], id: 'house.open-armchair.l-and-grandpa-s' },
    ] },
    { id: 'house.open-armchair-2', verb: ['open', 'pull', 'push', 'use'], a: 'armchair', do: [{ say: ['hero', 'Just crumbs. Old crumbs.'], id: 'house.open-armchair-2.l-just-crumbs-old' }] },
    { id: 'house.look-armchair', verb: 'look', a: 'armchair', if: { prop: ['armchair', 'searched'] }, do: [{ say: ['hero', 'Just an armchair now. A comfy one.'], id: 'house.look-armchair.l-just-an-armchair' }] },

    // The pantry, and the finale.
    { id: 'house.look-pantry', verb: 'look', a: 'pantry', if: { prop: ['pantry', 'open'] }, do: [{ say: ['hero', 'Open. An empty tin. A happy cat.'], id: 'house.look-pantry.l-open-an-empty' }] },
    { id: 'house.open-pantry', verb: ['open', 'use', 'pull'], a: 'pantry', if: { prop: ['pantry', 'locked'] }, do: [{ play: ['pantry', 'rattle'] }, { say: ['hero', 'Locked. I need the key.'], id: 'house.open-pantry.l-locked-i-need' }] },
    { id: 'house.use-key-pantry', verb: 'use', a: 'key', b: 'pantry', if: { prop: ['pantry', 'locked'] }, do: [
      { cutscene: [
        { sfx: 'metal' }, { wait: 300 }, { sfx: 'latch' }, { prop: ['pantry', 'open'] }, { sfx: 'door_open' },
        { used: 'key' }, { set: 'pantry_open' },
        { say: ['hero', 'Open! Sardines! Hello, my little friends.'], id: 'house.use-key-pantry.l-open-sardines' },
        { pose: ['hero', 'eat'] }, { sfx: 'chips' }, { wait: 1400 },
        { pose: ['biscuit', 'idle'] }, { id: 'house.use-key-pantry.l-mrrp-did-someone', say: ['biscuit', 'Mrrp? Did someone say sardines?'] },
        { face: 'biscuit', who: 'grandma' },
        { id: 'house.use-key-pantry.l-ha-two-cats-one', say: ['grandma', 'Ha! Two cats, one tin. Share, you two.'] },
        { pose: ['hero', 'idle'] }, { say: ['hero', 'Fine. Half. Ish.'], id: 'house.use-key-pantry.l-fine-half-ish' },
        // A custom command of the game (index.ts `commands`): stars over the scene, no effect on the state.
        { custom: 'sparkle', args: { ms: 1400 } },
      ] },
      { ending: true, after: [
        { id: 'house.use-key-pantry.l-well-done-pixel', say: ['grandma', 'Well done, Pixel. Best breakfast ever.'] },
        { say: ['hero', 'Best. Breakfast. Ever.'], id: 'house.use-key-pantry.l-best-breakfast' },
      ] },
    ] },

    // Small gags (the way out is the `window` exit above).
    { id: 'house.open-door', verb: 'open', a: 'door', do: [{ say: ['hero', 'The hall. The vacuum cleaner lives there. Our sworn enemy.'], id: 'house.open-door.l-the-hall-the' }] },
    // Biscuit (the second playable cat) is the one who drinks tea.
    { id: 'house.take-teacup', verb: ['take', 'use'], a: 'teacup', if: { player: 'biscuit' }, do: [{ id: 'house.take-teacup.nth', nth: [[{ sfx: 'glass' }, { say: ['hero', 'Lukewarm tea. Biscuit approves.'], id: 'house.take-teacup.nth.l-lukewarm-tea' }, { set: 'tea_drunk' }], [{ say: ['hero', 'Empty. Biscuit regrets nothing.'], id: 'house.take-teacup.nth.l-empty-biscuit' }]] }] },
    { id: 'house.take-teacup-2', verb: 'take', a: 'teacup', do: [{ say: ['hero', 'Hot tea and cat paws. No.'], id: 'house.take-teacup-2.l-hot-tea-and-cat' }] },
    { id: 'house.push-clock', verb: 'push', a: 'clock', do: [{ say: ['hero', 'Heavy. And it judges me.'], id: 'house.push-clock.l-heavy-and-it' }] },
    { id: 'house.take-bookshelf', verb: 'take', a: 'bookshelf', do: [{ say: ['hero', 'A book falls. "Knitting for beginners." I put it back.'], id: 'house.take-bookshelf.l-a-book-falls' }] },
  ],

  talk: {
    grandma: [
      { id: 'house.grandma.where-is-the-key', topic: 'Where is the key?', do: [
        { id: 'house.grandma.where-is-the-key.l-grandpa-had-it', say: ['grandma', 'Grandpa had it last. He is in the garden, fixing the pipes.'] },
        { if: { not: { unlocked: 'garden' } }, then: [{ unlock: 'garden' }, { id: 'house.grandma.where-is-the-key.l-new-on-the-map', toast: 'New on the map: the garden' }] },
        { id: 'house.grandma.where-is-the-key.l-go-through-the', say: ['grandma', 'Go through the big window. Mind the roses.'] },
      ] },
      { id: 'house.grandma.what-is-for-dinner', topic: 'What is for dinner?', do: [
        { id: 'house.grandma.what-is-for-dinner.nth', nth: [
          [{ id: 'house.grandma.what-is-for-dinner.nth.l-sardines-if-we', say: ['grandma', 'Sardines. If we find the key.'] }],
          [{ id: 'house.grandma.what-is-for-dinner.nth.l-still-sardines', say: ['grandma', 'Still sardines.'] }],
          [{ id: 'house.grandma.what-is-for-dinner.nth.l-pixel-sardines', say: ['grandma', 'Pixel. Sardines. Go.'] }],
        ] },
      ] },
      { id: 'house.grandma.why-lock-the-sardines', topic: 'Why lock the sardines?', do: [
        { id: 'house.grandma.why-lock-the-sardines.l-because-a', say: ['grandma', 'Because a certain cat opens cupboards. A certain grey cat.'] },
        { say: ['hero', 'Biscuit. Definitely Biscuit.'], id: 'house.grandma.why-lock-the-sardines.l-biscuit-definite' },
      ] },
      { id: 'house.grandma.i-found-the-key', topic: 'I found the key!', if: { has: 'key' }, do: [{ id: 'house.grandma.i-found-the-key.l-then-what-are', say: ['grandma', 'Then what are you waiting for? Open the pantry!'] }] },
    ],
    grandpa: [
      { id: 'house.grandpa.why-are-you-home', topic: 'Why are you home?', do: [{ id: 'house.grandpa.why-are-you-home.l-a-cat-with-a-key', say: ['grandpa', 'A cat with a key. I had to see this.'] }, { pose: ['grandpa', 'laugh'] }, { wait: 700 }, { pose: ['grandpa', 'idle'] }] },
      { id: 'house.grandpa.you-carried-the-armchair', topic: 'You carried the armchair back?', do: [{ id: 'house.grandpa.you-carried-the-armchair.l-it-walked-i-only', say: ['grandpa', 'It walked. I only steered.'] }, { say: ['hero', 'Armchairs. Full of secrets.'], id: 'house.grandpa.you-carried-the-armchair.l-armchairs-full' }] },
    ],
  },

  // Hints from the shell phone (Grandma's voice), in puzzle order.
  hints: [
    { until: { unlocked: 'garden' }, lines: ['Ask me where the key is, sweetie.'] },
    { until: { prop: ['armchair', 'searched'] }, lines: ['Grandpa\'s armchair eats everything. Look behind the cushion.', 'Open the armchair, sweetie. Or pull it.'] },
    { until: 'tank_drained', lines: ['Grandpa is in the garden. Go through the big window.'] },
    { until: { unlocked: 'market' }, lines: ['Something came out of the water tank, no? Read it, then call Lou.'] },
    { until: { has: 'key' }, lines: ['The key is at the market. Open the map.'] },
    { until: 'pantry_open', lines: ['You have the key! Use it on the pantry cupboard.'] },
  ],

  onEnter: [
    { if: { has: 'key' }, then: [{ id: 'house.enter.once', once: [{ say: ['hero', 'Home! Pantry, here I come.'], id: 'house.enter.once.l-home-pantry-here' }] }] },
    { if: { actorIn: ['grandpa', 'house'] }, then: [{ id: 'house.enter.once-2', once: [{ id: 'house.enter.once-2.l-pixel-i-beat-you', say: ['grandpa', 'Pixel! I beat you home. The armchair is faster than it looks.'] }] }] },
  ],

  // Biscuit lives his own life: a stretch every so often, on its own, between the player's actions.
  scripts: [
    { stepIds: ['biscuit_naps.wait', 'biscuit_naps.anim'], id: 'biscuit_naps', loop: true, do: [{ wait: 7000 }, { anim: ['biscuit', 'stretch'], ms: 1200 }] },
  ],
});
